import { execFile } from "node:child_process"
import * as fs from "node:fs/promises"

import { defineConfig } from "electron-vite"
import appPlugin from "@opencode-ai/app/vite"

const OPENCODE_SERVER_DIST = "../opencode/dist/node"

const channel = (() => {
  const raw = process.env.OPENCODE_CHANNEL
  if (raw === "dev" || raw === "beta" || raw === "prod") return raw
  if (process.env.OPENCODE_CHANNEL === "latest") return "prod"
  return "dev"
})()

const nodePtyPkg = `@lydell/node-pty-${process.platform}-${process.arch}`

// Electron-vite 5's ESM shim scans generated chunks with a regex. The server
// bundle contains source-code strings with `require(...)` and `import ...`,
// which can make that scan insert the shim inside a string literal. Put the
// real shim in the chunk first so electron-vite detects it and leaves it alone.
const ELECTRON_CJS_SHIM = `
// -- CommonJS Shims --
import __cjs_mod__ from 'node:module';
const __filename = import.meta.filename;
const __dirname = import.meta.dirname;
const require = __cjs_mod__.createRequire(import.meta.url);
`

const NODE_STUB_EXPORT_NAMES = [
  "Abortable",
  "AddressInfo",
  "Agent",
  "AnyRecord",
  "Assert",
  "AssertMethodNames",
  "AssertOptions",
  "AssertPredicate",
  "AssertStrict",
  "AssertionError",
  "AssertionErrorOptions",
  "AsyncCompleter",
  "AsyncLocalStorage",
  "AsyncResource",
  "AsyncResourceOptions",
  "BigIntStats",
  "BigIntStatsFs",
  "BinaryLike",
  "Blob",
  "BlockList",
  "Buffer",
  "BufferEncodingOption",
  "CaaRecord",
  "CallTracker",
  "CallTrackerCall",
  "CallTrackerReportInformation",
  "ClientRequestArgs",
  "Completer",
  "CompleterResult",
  "ConnectionOptions",
  "Context",
  "Control",
  "CopyOptions",
  "DatabaseSync",
  "Dir",
  "Direction",
  "Dirent",
  "Duplex",
  "EOL",
  "EncodingOption",
  "EventData",
  "EventEmitter",
  "EventEmitterAsyncResource",
  "File",
  "FinishedOptions",
  "GlobOptions",
  "GlobOptionsWithFileTypes",
  "GlobOptionsWithoutFileTypes",
  "ImportAttributes",
  "ImportPhase",
  "IncomingHttpHeaders",
  "IncomingMessage",
  "InspectOptions",
  "Interface",
  "IpcNetConnectOpts",
  "KeyObject",
  "LookupAddress",
  "LookupAllOptions",
  "LookupFunction",
  "LookupOneOptions",
  "LookupOptions",
  "MIMEType",
  "MakeDirectoryOptions",
  "MessageChannel",
  "MessageOptions",
  "MessagePort",
  "Mode",
  "MxRecord",
  "NaptrRecord",
  "NodeEventTarget",
  "NonSharedBuffer",
  "ObjectEncodingOptions",
  "OpenDirOptions",
  "OpenMode",
  "OutgoingHttpHeaders",
  "ParsedUrlQuery",
  "ParsedUrlQueryInput",
  "PassThrough",
  "PathLike",
  "PeerCertificate",
  "Performance",
  "PerformanceEntry",
  "PerformanceMark",
  "PerformanceMeasure",
  "PerformanceObserver",
  "PerformanceObserverEntryList",
  "PerformanceResourceTiming",
  "PipelineDestination",
  "PipelineOptions",
  "PipelinePromise",
  "PipelineSource",
  "PipelineTransform",
  "ReadLineOptions",
  "ReadOptions",
  "ReadOptionsWithBuffer",
  "ReadPosition",
  "ReadStream",
  "ReadVResult",
  "Readable",
  "RecordWithTtl",
  "ResolveOptions",
  "ResolveWithTtlOptions",
  "Resolver",
  "ResolverOptions",
  "RmDirOptions",
  "RmOptions",
  "SendHandle",
  "Server",
  "ServerResponse",
  "SoaRecord",
  "Socket",
  "SrvRecord",
  "StatFsOptions",
  "StatOptions",
  "Stats",
  "StatsFs",
  "Stream",
  "StringDecoder",
  "TLSSocket",
  "TcpNetConnectOpts",
  "TcpSocketConnectOpts",
  "TextDecoder",
  "TextEncoder",
  "TimeLike",
  "TimerOptions",
  "TlsaRecord",
  "Transferable",
  "Transform",
  "TransformOptions",
  "URL",
  "URLSearchParams",
  "UrlObject",
  "WASI",
  "WatchEventType",
  "WatchOptions",
  "Worker",
  "Writable",
  "WriteStream",
  "WriteVResult",
  "X509Certificate",
  "aborted",
  "access",
  "accessSync",
  "addAbortListener",
  "allowedNodeEnvironmentFlags",
  "appendFile",
  "appendFileSync",
  "arch",
  "argv",
  "availableParallelism",
  "backup",
  "basename",
  "callbackify",
  "chdir",
  "chmod",
  "chmodSync",
  "chown",
  "chownSync",
  "close",
  "closeSync",
  "constants",
  "copyFile",
  "copyFileSync",
  "cp",
  "cpuUsage",
  "createConnection",
  "createContext",
  "createGzip",
  "createHash",
  "createHmac",
  "createHook",
  "createInterface",
  "createPrivateKey",
  "createPublicKey",
  "createReadStream",
  "createServer",
  "createWriteStream",
  "cwd",
  "debuglog",
  "deepStrictEqual",
  "deflate",
  "delimiter",
  "deprecate",
  "dirname",
  "dlopen",
  "doesNotMatch",
  "doesNotReject",
  "doesNotThrow",
  "emitKeypressEvents",
  "emitWarning",
  "env",
  "eventLoopUtilization",
  "exec",
  "execFile",
  "execFileSync",
  "executionAsyncId",
  "executionAsyncResource",
  "exists",
  "existsSync",
  "exit",
  "extname",
  "fail",
  "fdatasync",
  "fileURLToPath",
  "findPackageJSON",
  "finished",
  "fork",
  "format",
  "fstat",
  "fstatSync",
  "fsync",
  "ftruncate",
  "generateKeyPairSync",
  "getActiveResourcesInfo",
  "getCallSites",
  "getEventListeners",
  "getMaxListeners",
  "glob",
  "globSync",
  "hrtime",
  "ifError",
  "inspect",
  "isAbsolute",
  "isMainThread",
  "join",
  "link",
  "linkSync",
  "listenerCount",
  "loadEnvFile",
  "lstat",
  "lstatSync",
  "markAsUntransferable",
  "match",
  "mkdir",
  "mkdirSync",
  "mkdtemp",
  "mkdtempSync",
  "mock",
  "monitorEventLoopDelay",
  "nextTick",
  "normalize",
  "notDeepStrictEqual",
  "notStrictEqual",
  "ok",
  "on",
  "once",
  "open",
  "openAsBlob",
  "openSync",
  "opendir",
  "opendirSync",
  "parentPort",
  "parse",
  "parseArgs",
  "parseEnv",
  "partialDeepStrictEqual",
  "pathToFileURL",
  "performance",
  "pid",
  "pipeline",
  "platform",
  "posix",
  "ppid",
  "promises",
  "promisify",
  "randomBytes",
  "randomUUID",
  "read",
  "readFile",
  "readFileSync",
  "readSync",
  "readdir",
  "readdirSync",
  "readlink",
  "readlinkSync",
  "readv",
  "realpath",
  "realpathSync",
  "receiveMessageOnPort",
  "rejects",
  "relative",
  "rename",
  "renameSync",
  "request",
  "resolve",
  "resourceUsage",
  "rm",
  "rmSync",
  "rmdir",
  "rmdirSync",
  "run",
  "runInContext",
  "sep",
  "setMaxListeners",
  "setTimeout",
  "spawn",
  "spawnSync",
  "stat",
  "statSync",
  "stderr",
  "stdin",
  "stdout",
  "strict",
  "strictEqual",
  "stripTypeScriptTypes",
  "stripVTControlCharacters",
  "styleText",
  "symlink",
  "symlinkSync",
  "syncBuiltinESMExports",
  "test",
  "threadId",
  "throws",
  "timeout",
  "timerify",
  "tmpdir",
  "transcode",
  "triggerAsyncId",
  "truncate",
  "truncateSync",
  "types",
  "unlink",
  "unlinkSync",
  "unwatchFile",
  "unzip",
  "urlToHttpOptions",
  "utimes",
  "utimesSync",
  "validateHeaderName",
  "validateHeaderValue",
  "version",
  "versions",
  "watch",
  "watchFile",
  "webcrypto",
  "win32",
  "write",
  "writeFile",
  "writeFileSync",
  "writeSync",
  "writev",
  "writevSync",
]

// HSCode: Sentry sourcemap 上传插件已彻底移除（隐私清理），构建产物不再上传到 Sentry

export default defineConfig({
  main: {
    define: {
      "import.meta.env.OPENCODE_CHANNEL": JSON.stringify(channel),
    },
    build: {
      rollupOptions: {
        input: {
          index: "src/main/index.ts",
          sidecar: "src/main/sidecar.ts",
          // HSCode Network Inspector: capture worker must be a separate bundle
          // entry, otherwise `new Worker(...)` at runtime points to a .ts file
          // that does not exist in out/main → MODULE_NOT_FOUND / instant crash.
          "capture-worker": "src/main/network/capture-worker.ts",
        },
      },
      externalizeDeps: { include: [nodePtyPkg] },
    },
    plugins: [
      {
        name: "hscode:preempt-electron-vite-cjs-shim",
        enforce: "pre",
        renderChunk(code, _chunk, { format }) {
          if (format !== "es" || code.includes(ELECTRON_CJS_SHIM)) return
          if (!/__filename|__dirname|require\(|require\.resolve\(/.test(code)) return
          return { code: ELECTRON_CJS_SHIM + code, map: null }
        },
      },
      {
        name: "opencode:node-pty-narrower",
        enforce: "pre",
        resolveId(s) {
          if (s === "@lydell/node-pty") return nodePtyPkg
        },
      },
      {
        name: "opencode:virtual-server-module",
        enforce: "pre",
        resolveId(id) {
          if (id === "virtual:opencode-server") return this.resolve(`${OPENCODE_SERVER_DIST}/node.js`)
        },
      },
      {
        name: "opencode:copy-server-assets",
        async writeBundle() {
          for (const l of await fs.readdir(OPENCODE_SERVER_DIST)) {
            if (!l.endsWith(".wasm")) continue
            await fs.writeFile(`./out/main/chunks/${l}`, await fs.readFile(`${OPENCODE_SERVER_DIST}/${l}`))
          }
        },
      },
    ],
  },
  preload: {
    build: {
      rollupOptions: {
        input: { index: "src/preload/index.ts" },
        output: {
          format: "cjs",
          entryFileNames: "[name].js",
        },
      },
    },
  },
  renderer: {
    plugins: [
      appPlugin,
      {
        name: "hscode:renderer-node-stub",
        enforce: "pre",
        resolveId(id) {
          const BARE = new Set([
            "fs", "fs/promises", "path", "path/posix", "path/win32", "stream", "stream/promises", "stream/web",
            "http", "https", "crypto", "os", "net", "tls", "url", "util", "util/types", "zlib", "events",
            "child_process", "readline", "readline/promises", "buffer", "process", "string_decoder", "assert",
            "assert/strict", "querystring", "module", "tty", "dns", "dns/promises", "timers", "timers/promises",
            "vm", "worker_threads", "async_hooks", "perf_hooks", "trace_events", "v8", "domain",
            "punycode", "sys", "wasi", "constants",
          ])
          const name = id.startsWith("node:") ? id.slice(5) : id
          if (id.startsWith("node:") || BARE.has(name)) return "hscode-virtual-node-stub:node:" + name
        },
        load(id) {
          if (!id.startsWith("hscode-virtual-node-stub:node:")) return
          const prelude = "const noop = () => {}"
          const stub = { __isNodeStub: true }
          return (
            prelude +
            "\nexport default stub\n" +
            NODE_STUB_EXPORT_NAMES.map((n) => `export const ${n} = noop`).join("\n")
          )
        },
      },
    ],
    publicDir: "../../../app/public",
    root: "src/renderer",
    build: {
      sourcemap: true,
      rollupOptions: {
        input: {
          main: "src/renderer/index.html",
        },
      },
    },
  },
})
