import { execFile } from "node:child_process"
import * as fs from "node:fs/promises"

import { defineConfig } from "electron-vite"
import appPlugin from "@opencode-ai/app/vite"

const OPENCODE_SERVER_DIST = "../opencode/dist/node"

const channel = (() => {
  const raw = process.env.OPENCODE_CHANNEL
  if (raw === "dev" || raw === "beta" || raw === "prod") return raw
  if (process.env.OPENCODE_CHANNEL === "latest") return "prod"
  return "dev"
})()

const nodePtyPkg = `@lydell/node-pty-${process.platform}-${process.arch}`

// Per-module named exports enumerated from the node-only packages
// (@effect/platform-node*, undici, llm protocols) that the renderer graph
// statically reaches through lazy code paths but never executes.
const NODE_STUB_EXPORTS = {
  assert: ["Assert", "AssertionError", "AssertionErrorOptions", "CallTracker", "deepStrictEqual", "doesNotMatch", "doesNotReject", "doesNotThrow", "fail", "ifError", "match", "notDeepStrictEqual", "notStrictEqual", "ok", "partialDeepStrictEqual", "rejects", "strict", "strictEqual", "throws"],
  buffer: ["Blob", "Buffer", "File", "transcode"],
  crypto: ["createHash", "createHmac", "randomBytes", "randomUUID", "webcrypto"],
  dns: ["promises", "Resolver"],
  events: ["EventEmitter", "addAbortListener", "getEventListeners", "getMaxListeners", "listenerCount", "on", "once", "setMaxListeners"],
  fs: ["access", "accessSync", "appendFile", "appendFileSync", "chmod", "close", "closeSync", "constants", "copyFile", "copyFileSync", "createReadStream", "createWriteStream", "Dir", "Dirent", "exists", "existsSync", "glob", "globSync", "lstatSync", "mkdir", "mkdtemp", "open", "openAsBlob", "openSync", "readFile", "readFileSync", "readdirSync", "ReadStream", "rename", "stat", "Stats", "symlink", "truncate", "unlink", "WatchOptions", "watchFile", "writeFile", "WriteStream"],
  http: ["Agent", "createServer", "IncomingMessage", "request", "ServerResponse", "validateHeaderName", "validateHeaderValue"],
  https: ["Agent", "request"],
  module: ["findPackageJSON", "stripTypeScriptTypes", "syncBuiltinESMExports"],
  net: ["BlockList", "createServer", "Server", "Socket"],
  os: ["EOL", "availableParallelism", "constants", "tmpdir"],
  path: ["basename", "dirname", "extname", "isAbsolute", "join", "parse", "posix", "relative", "resolve", "sep", "win32"],
  process: ["arch", "argv", "chdir", "cpuUsage", "cwd", "env", "exit", "hrtime", "nextTick", "pid", "platform", "ppid", "stderr", "stdin", "stdout", "version", "versions"],
  readline: ["createInterface", "emitKeypressEvents", "Interface"],
  sqlite: ["DatabaseSync"],
  stream: ["Duplex", "finished", "pipeline", "Readable", "Stream", "Transform", "Writable"],
  timers: ["setTimeout"],
  tls: ["TLSSocket"],
  tty: ["WriteStream"],
  url: ["fileURLToPath", "pathToFileURL", "URL", "URLSearchParams", "urlToHttpOptions"],
  util: ["TextDecoder", "TextEncoder", "aborted", "callbackify", "debuglog", "inspect", "promisify", "styleText", "types"],
  vm: ["createContext", "runInContext"],
  wasi: ["WASI"],
  zlib: ["createGzip", "deflate", "unzip"],
}

// HSCode: Sentry sourcemap 上传插件已彻底移除（隐私清理），构建产物不再上传到 Sentry

const NODE_STUB_EXPORT_NAMES = [
  "Abortable",
  "AddressInfo",
  "Agent",
  "AnyRecord",
  "Assert",
  "AssertMethodNames",
  "AssertOptions",
  "AssertPredicate",
  "AssertStrict",
  "AssertionError",
  "AssertionErrorOptions",
  "AsyncCompleter",
  "AsyncLocalStorage",
  "AsyncResource",
  "AsyncResourceOptions",
  "BigIntStats",
  "BigIntStatsFs",
  "BinaryLike",
  "Blob",
  "BlockList",
  "Buffer",
  "BufferEncodingOption",
  "CaaRecord",
  "CallTracker",
  "CallTrackerCall",
  "CallTrackerReportInformation",
  "ClientRequestArgs",
  "Completer",
  "CompleterResult",
  "ConnectionOptions",
  "Context",
  "Control",
  "CopyOptions",
  "DatabaseSync",
  "Dir",
  "Direction",
  "Dirent",
  "Duplex",
  "EOL",
  "EncodingOption",
  "EventData",
  "EventEmitter",
  "EventEmitterAsyncResource",
  "File",
  "FinishedOptions",
  "GlobOptions",
  "GlobOptionsWithFileTypes",
  "GlobOptionsWithoutFileTypes",
  "ImportAttributes",
  "ImportPhase",
  "IncomingHttpHeaders",
  "IncomingMessage",
  "InspectOptions",
  "Interface",
  "IpcNetConnectOpts",
  "KeyObject",
  "LookupAddress",
  "LookupAllOptions",
  "LookupFunction",
  "LookupOneOptions",
  "LookupOptions",
  "MIMEType",
  "MakeDirectoryOptions",
  "MessageChannel",
  "MessageOptions",
  "MessagePort",
  "Mode",
  "MxRecord",
  "NaptrRecord",
  "NodeEventTarget",
  "NonSharedBuffer",
  "ObjectEncodingOptions",
  "OpenDirOptions",
  "OpenMode",
  "OutgoingHttpHeaders",
  "ParsedUrlQuery",
  "ParsedUrlQueryInput",
  "PathLike",
  "PeerCertificate",
  "Performance",
  "PerformanceEntry",
  "PerformanceMark",
  "PerformanceMeasure",
  "PerformanceObserver",
  "PerformanceObserverEntryList",
  "PerformanceResourceTiming",
  "PipelineDestination",
  "PipelineOptions",
  "PipelinePromise",
  "PipelineSource",
  "PipelineTransform",
  "ReadLineOptions",
  "ReadOptions",
  "ReadOptionsWithBuffer",
  "ReadPosition",
  "ReadStream",
  "ReadVResult",
  "Readable",
  "RecordWithTtl",
  "ResolveOptions",
  "ResolveWithTtlOptions",
  "Resolver",
  "ResolverOptions",
  "RmDirOptions",
  "RmOptions",
  "SendHandle",
  "Server",
  "ServerResponse",
  "SoaRecord",
  "Socket",
  "SrvRecord",
  "StatFsOptions",
  "StatOptions",
  "Stats",
  "StatsFs",
  "Stream",
  "StringDecoder",
  "TLSSocket",
  "TcpNetConnectOpts",
  "TcpSocketConnectOpts",
  "TextDecoder",
  "TextEncoder",
  "TimeLike",
  "TimerOptions",
  "TlsaRecord",
  "Transferable",
  "Transform",
  "TransformOptions",
  "URL",
  "URLSearchParams",
  "UrlObject",
  "WASI",
  "WatchEventType",
  "WatchOptions",
  "Worker",
  "Writable",
  "WriteStream",
  "WriteVResult",
  "X509Certificate",
  "aborted",
  "access",
  "accessSync",
  "addAbortListener",
  "allowedNodeEnvironmentFlags",
  "appendFile",
  "appendFileSync",
  "arch",
  "argv",
  "availableParallelism",
  "backup",
  "basename",
  "callbackify",
  "chdir",
  "chmod",
  "chown",
  "close",
  "closeSync",
  "constants",
  "copyFile",
  "copyFileSync",
  "cp",
  "cpuUsage",
  "createConnection",
  "createContext",
  "createGzip",
  "createHash",
  "createHmac",
  "createHook",
  "createInterface",
  "createReadStream",
  "createServer",
  "createWriteStream",
  "cwd",
  "debuglog",
  "deepStrictEqual",
  "deflate",
  "deprecate",
  "dirname",
  "dlopen",
  "doesNotMatch",
  "doesNotReject",
  "doesNotThrow",
  "emitKeypressEvents",
  "emitWarning",
  "env",
  "eventLoopUtilization",
  "exec",
  "execFile",
  "execFileSync",
  "executionAsyncId",
  "executionAsyncResource",
  "exists",
  "existsSync",
  "exit",
  "fail",
  "fileURLToPath",
  "findPackageJSON",
  "finished",
  "fork",
  "fstat",
  "fsync",
  "ftruncate",
  "getActiveResourcesInfo",
  "getCallSites",
  "getEventListeners",
  "getMaxListeners",
  "glob",
  "globSync",
  "hrtime",
  "ifError",
  "inspect",
  "isAbsolute",
  "isMainThread",
  "join",
  "link",
  "listenerCount",
  "loadEnvFile",
  "lstatSync",
  "markAsUntransferable",
  "match",
  "mkdir",
  "mkdtemp",
  "mock",
  "monitorEventLoopDelay",
  "nextTick",
  "notDeepStrictEqual",
  "notStrictEqual",
  "ok",
  "on",
  "once",
  "open",
  "openAsBlob",
  "openSync",
  "parentPort",
  "parse",
  "parseArgs",
  "parseEnv",
  "partialDeepStrictEqual",
  "pathToFileURL",
  "performance",
  "pid",
  "pipeline",
  "platform",
  "posix",
  "ppid",
  "promises",
  "promisify",
  "randomBytes",
  "randomUUID",
  "read",
  "readFile",
  "readFileSync",
  "readdir",
  "readdirSync",
  "readlink",
  "realpath",
  "receiveMessageOnPort",
  "rejects",
  "rename",
  "request",
  "resolve",
  "resourceUsage",
  "rm",
  "run",
  "runInContext",
  "sep",
  "setMaxListeners",
  "setTimeout",
  "spawn",
  "spawnSync",
  "stat",
  "stderr",
  "stdin",
  "stdout",
  "strict",
  "strictEqual",
  "stripTypeScriptTypes",
  "stripVTControlCharacters",
  "styleText",
  "symlink",
  "syncBuiltinESMExports",
  "test",
  "threadId",
  "throws",
  "timerify",
  "tmpdir",
  "transcode",
  "triggerAsyncId",
  "truncate",
  "types",
  "unlink",
  "unzip",
  "urlToHttpOptions",
  "utimes",
  "validateHeaderName",
  "validateHeaderValue",
  "version",
  "versions",
  "watch",
  "watchFile",
  "webcrypto",
  "win32",
  "write",
  "writeFile",
]

export default defineConfig({
  main: {
    define: {
      "import.meta.env.OPENCODE_CHANNEL": JSON.stringify(channel),
    },
    build: {
      rollupOptions: {
        input: {
          index: "src/main/index.ts",
          sidecar: "src/main/sidecar.ts",
          // HSCode Network Inspector: capture worker must be a separate bundle
          // entry, otherwise `new Worker(...)` at runtime points to a .ts file
          // that does not exist in out/main → MODULE_NOT_FOUND / instant crash.
          "capture-worker": "src/main/network/capture-worker.ts",
        },
        // Keep this identical to electron-vite's Node 20.11+ shim. Its regex insertion can
        // corrupt bundled TypeScript, while a Rollup banner places the shim safely.
        output: {
          banner: `
// -- CommonJS Shims --
import __cjs_mod__ from 'node:module';
const __filename = import.meta.filename;
const __dirname = import.meta.dirname;
const require = __cjs_mod__.createRequire(import.meta.url);
`,
        },
      },
      externalizeDeps: { include: [nodePtyPkg] },
    },
    plugins: [
      {
        name: "opencode:node-pty-narrower",
        enforce: "pre",
        resolveId(s) {
          if (s === "@lydell/node-pty") return nodePtyPkg
        },
      },
      {
        name: "opencode:virtual-server-module",
        enforce: "pre",
        resolveId(id) {
          if (id === "virtual:opencode-server") return this.resolve(`${OPENCODE_SERVER_DIST}/node.js`)
        },
      },
      {
        name: "opencode:copy-server-assets",
        async writeBundle() {
          for (const l of await fs.readdir(OPENCODE_SERVER_DIST)) {
            if (!l.endsWith(".wasm")) continue
            await fs.writeFile(`./out/main/chunks/${l}`, await fs.readFile(`${OPENCODE_SERVER_DIST}/${l}`))
          }
        },
      },
    ],
  },
  preload: {
    build: {
      rollupOptions: {
        input: { index: "src/preload/index.ts" },
        output: {
          format: "cjs",
          entryFileNames: "[name].js",
        },
      },
    },
  },
  renderer: {
    plugins: [
      appPlugin,
      {
        // Renderer stub for node builtins: the app graph statically reaches
        // node-only packages (@effect/platform-node*, undici, llm protocols)
        // through lazy code paths that never execute in the renderer. Stub
        // every node: import so the production build passes; a missing named
        // export fails the build with the exact name to add above.
        name: "hscode:renderer-node-stub",
        enforce: "pre",
        resolveId(id) {
          if (id.startsWith("node:")) return "\0hscode-node-stub:" + id
        },
        load(id) {
          const marker = " hscode-node-stub:node:"
          if (!id.startsWith(marker)) return
          if (!id.includes("hscode-node-stub")) return
          const prelude = "const noop = () => {}"
          return prelude + "\n" + NODE_STUB_EXPORT_NAMES.map((n) => `export const ${n} = noop`).join("\n")
          return lines.join("\n")
        },
      },
    ],
    publicDir: "../../../app/public",
    root: "src/renderer",
    build: {
      sourcemap: true,
      rollupOptions: {
        input: {
          main: "src/renderer/index.html",
        },
      },
    },
  },
})
